// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/order_repository.go -destination=mocks/mock_order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "order-service/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepository) Create(db *gorm.DB, arg1 *entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(db, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), db, arg1)
}

// FindById mocks base method.
func (m *MockOrderRepository) FindById(db *gorm.DB, ctx context.Context, order *entity.Order, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", db, ctx, order, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindById indicates an expected call of FindById.
func (mr *MockOrderRepositoryMockRecorder) FindById(db, ctx, order, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockOrderRepository)(nil).FindById), db, ctx, order, id)
}

// FindByProductId mocks base method.
func (m *MockOrderRepository) FindByProductId(db *gorm.DB, ctx context.Context, orders *[]entity.Order, productId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductId", db, ctx, orders, productId)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindByProductId indicates an expected call of FindByProductId.
func (mr *MockOrderRepositoryMockRecorder) FindByProductId(db, ctx, orders, productId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductId", reflect.TypeOf((*MockOrderRepository)(nil).FindByProductId), db, ctx, orders, productId)
}

// List mocks base method.
func (m *MockOrderRepository) List(db *gorm.DB, ctx context.Context, orders *[]entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", db, ctx, orders)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockOrderRepositoryMockRecorder) List(db, ctx, orders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderRepository)(nil).List), db, ctx, orders)
}
