// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gateway/http/product_gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/gateway/http/product_gateway.go -destination=internal/mocks/mock_product_gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "order-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductGateway is a mock of ProductGateway interface.
type MockProductGateway struct {
	ctrl     *gomock.Controller
	recorder *MockProductGatewayMockRecorder
	isgomock struct{}
}

// MockProductGatewayMockRecorder is the mock recorder for MockProductGateway.
type MockProductGatewayMockRecorder struct {
	mock *MockProductGateway
}

// NewMockProductGateway creates a new mock instance.
func NewMockProductGateway(ctrl *gomock.Controller) *MockProductGateway {
	mock := &MockProductGateway{ctrl: ctrl}
	mock.recorder = &MockProductGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductGateway) EXPECT() *MockProductGatewayMockRecorder {
	return m.recorder
}

// GetProductInfo mocks base method.
func (m *MockProductGateway) GetProductInfo(productId string) (*model.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductInfo", productId)
	ret0, _ := ret[0].(*model.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductInfo indicates an expected call of GetProductInfo.
func (mr *MockProductGatewayMockRecorder) GetProductInfo(productId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductInfo", reflect.TypeOf((*MockProductGateway)(nil).GetProductInfo), productId)
}
