// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gateway/messaging/producer.go
//
// Generated by this command:
//
//	mockgen -source=internal/gateway/messaging/producer.go -destination=internal/mocks/mock_producer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "order-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducer is a mock of Producer interface.
type MockProducer[T model.Event] struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder[T]
	isgomock struct{}
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder[T model.Event] struct {
	mock *MockProducer[T]
}

// NewMockProducer creates a new mock instance.
func NewMockProducer[T model.Event](ctrl *gomock.Controller) *MockProducer[T] {
	mock := &MockProducer[T]{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer[T]) EXPECT() *MockProducerMockRecorder[T] {
	return m.recorder
}

// Send mocks base method.
func (m *MockProducer[T]) Send(pattern string, event T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", pattern, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockProducerMockRecorder[T]) Send(pattern, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockProducer[T])(nil).Send), pattern, event)
}
